spring.application.name=ticketingservicespringboot

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/ticketing_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
