spring.application.name=ticketingservicespringboot

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/ticketing_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate : CHANGE THE .ddl-auto to UPDATE DURING PRODUCTION
spring.jpa.hibernate.ddl-auto=create    
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


aws.s3.bucket=${AWS_S3_BUCKET}
aws.region=${AWS_REGION:us-east-1}
aws.cdn.url=${AWS_CDN_URL}